### ISSUE TITLE
Not working with Worms3/Sixaxis

### ISSUE THREAD

**Issue by bru7us** [meancoot/MFiWrapper#1]
I'd be happy to help with some beta testing of this project in the case that I can support.
I'm not sure how much you expect to be working right now, but from scanning the code it looks ready for basic functionality tests.

I have: iPhone4, iOS7.0.4, Worms3, SIXAXIS (non-DS) wireless controller (I also have a DS3 if needed).

Last night I set up Theos, ldid and your source, installed BTstack on my phone and copied libBTstack.dylib to $THEOS/lib; Ran 'make package' and installed the resulting deb on my device.

I changed the setting to use BTstack and fired up the Worms game. Powered on the controller (already paired with the sixpair tool) and:
- The controller was found (screen changed from "Touch to continue" to "Press A to continue").
- The player 1 light on the controller did not light up (all lights went off).
- BTstack icon in my statusbar confirmed that there was a connection.
- No buttons were responding in the game.

Not sure where to go from here - but let me know if there is any way I can help by providing particular logs etc. I would love to have this working in Worms... the touch controls are a pain in the ass for several of the weapons.

**Comment by OMGsus** [comment]
Is worms3 capable mfi local multiplayer? 

Do any other games work with the latest code?

**Comment by bru7us** [comment]
Worms3 claims to offer "controller support" - and there are video reviews of a guy using CFA with it... not sure about multiplayer + controller.

**Comment by OMGsus** [comment]
I asked about multiplayer because I'm not sure if something is going on that affects ds3/sixaxis in games that have the possibility of multiplayer (iirc player gets set to -1 on ds3 right now) but I'm not sure how that's supposed to work. Hence the question.

I was also asking if you were able to have the controller register with other games.

Also, try setting BTStack's settings to "none." And see if MFi Wrapper invokes btstack on its own when an mfi game starts up. Then press the ps button. (CFA has the same issues with the same symptoms if it has to fight with btstack instances)

**Comment by meancoot** [comment]
Could you test again with the latest commit? .Make sure you run 'make clean' before building as there is no dependency tracking yet.

There is no reason to manually turn BTstack on (unless another app needs it), MFiWrapper will turn it on during startup. Make sure system BT is off and kill all other apps using BTstack for good measure.

I just tried Worms3 and found it to work as long as I wait until after the intro screens to connect the controller. If I connect it too soon the game will crash.

Neither the gamepad or the touch screen could be used to click the accept button during the tutorial missions. However I was able to play the Enter Sand Man mission without problems.

If you still have problems you should check back in a week or so. I've only recently got the code (which I copied from my work on RetroArch) all situated and will be fixing the bugs, and adding the few remaining features to the MFi code over the next couple of days.

**Comment by bru7us** [comment]
OK, I am happy to wait a bit if it's just not quite baked enough yet.

I followed the instructions you provided with very similar results to what I had been seeing.
- controller connects (no player light)
- screen changes to "press A..."
- game doesn't respond to any button presses
  This time I went a little further and touched the main page to proceed to the "campaign" menu - it was just auto-scrolling up without me doing anything. Went into the game and the "view" moved all the way to the left but my character didn't do anything.

I thought it might be because I have an Australian SIXAXIS (Model: CECHZC1A), so tried again with my US DS3 (CECHZC2U) with the same behaviour.

One variable I forgot to mention is that I have Xcode 5.0.2.. if that makes any difference?... and am compiling on MacOS 10.9

What iOS device was your successful test on?

**Comment by bru7us** [comment]
One more tidbit.... I just tried again (with both controllers separately) - this time only turning the controller on after entering the Campaign menu.

The player 1 light does come on - and the list scrolls all the way to the top - no inputs are accepted.

**Comment by meancoot** [comment]
It seems that when I copied to code over I never set it up to send the SixAxis startup packet on iOS. The autoscrolling happened because it was reading input values for an uninitialized buffer. (I've been testing with an 8-bitty and a WiiMote because I've been too lazy to pair a DualShock3 to my tablet.)

I testing and it should be working for Worms3 now.

**Comment by bru7us** [comment]
Yeah now its a lot happier!

One other bug for you to play with when you feel like it:
- I couldn't select anything in any context menus (weapon selection, pause menu)
- The weapon select menu has a "press Y for help" this works, but you can't back out (likely due to the previous line item)

On the bright side, the PS button works to get in and out of the pause menu...even if you can't use the menu to quit the game :) Navigating the main menu works fine too.

In thinking about what I just wrote - you already identified the bug yourself in the inability to click accept in the tutorials.

**Comment by OMGsus** [comment]
I just played Worms 3  (or tried to) using a legit wireless MFi Controller (SteelSeries Status) and it seems to behave the same way. (this was with MFiWrapper unistalled). 

Issues with legit wireless MFi Controller: (for comparison)

1) Player lights and actual connection is a crapshoot.
2) Menu navigation is sometimes guesswork.
3) Weapon select is non-navigatible and non-exitable. 
4) Pressing y is the only button that works from weapon select and that menu gets you further stuck.
5) exiting and coming back will show the pause menu and you can only un-pause. 

This all leads me to believe the wrapper is working as well as it can for this game and instead, this game's implementation of the game controller framework is buggy.

**Comment by bru7us** [comment]
Oh noes.... thanks for testing that - good to know.

Can you raise it as a bug with Team17? (email address and required format here: http://www.team17.com/support) - I would but I don't have a legit MFi.

Closing this issue now as it seems we've progressed as far as possible with the wrapper until the App offers better support.
