### ISSUE TITLE
Issue building in Mavericks

### ISSUE THREAD

**Issue by OMGsus** [meancoot/MFiWrapper#3]
For some reason, only in Mavericks, using theos proper, I'm having issues with:

```
 Linking tweak mfiwrapper...
ld: library not found for -lBTstack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [obj/mfiwrapper.dylib.ba964c90.unsigned] Error 1
make[1]: *** [internal-library-all_] Error 2
make: *** [mfiwrapper.all.tweak.variables] Error 2
```

I am able to build btstack and btstack examples. But I have to use the separate rpetrich-theos (kept separate, I switch where $THEOS points depending on which I'm building )

I have tried putting build libBTstack.dylib files in ld's search paths with no change.

Again, this only happens in my Mavericks VM.

**Comment by bru7us** [comment]
I had success with just dumping the libBTstack.dylib in $THEOS/lib

I'm on Mavericks (but on a MBP) and also has to use the rpetrich fork for btstack compilation. In the end, I didn't even use the BTstack lib I compiled, rather just copied in the one from my iPhone after installing the pre-compiled package from Cydia.

**Comment by OMGsus** [comment]
I tried copying in the one from my phone as well. Heh. I tried putting them in theos' lib too. 

I must be missing something simple. I'll reload the VM back to the original restore. I might have messed up my environment when I rebuilt some other projects for mavericks. 

Thanks, you gave me some things to look at.

**Comment by OMGsus** [comment]
I put the wrong libBTstack in the wrong $THEOS/lib :-/ 

That was it. Thanks!
