### ISSUE TITLE
Some games not invoking MFi in an expected way.

### ISSUE THREAD

**Issue by OMGsus** [meancoot/MFiWrapper#4]
Issue seen with "Oceanhorn" so far. 

Some games support MFi controllers, but links the GameController framework in an unexpected way (?), so btstack is never activated.

**Comment by meancoot** [comment]
I added a hook to start the backend whenever an observer for GCControllerDidConnectNotification is added to NSNotificationCenter. This fixes controller activation in Oceanhorn.

Previously it would start whenever the app started wireless controller discovery, but apparently Oceanhorn never calls that. Maybe Oceanhorn doesn't directly support wireless controllers?

I also have no idea why the game treats the Y Axis differently between the left thumbstick and the dpad. On the dpad the value -1.0 is considered up, but -1.0 is considered down on the left stick.

**Comment by OMGsus** [comment]
That's odd. I would have expected this specific game it to read the dpad's pressed states instead of the axes' floats based on the game's behavior. But it does other odd things as well that seem -incomplete- even with a legitimate MFi controller. 

Anywho. I'll test the latest now with the stratus, a ds3, and a classic controller and let you know if anything behaves out of the ordinary.

**Comment by OMGsus** [comment]
Ok, get this. These results are consistent now with oceanhorn and worms3 (I'm going to need to expand my MFi games library :-/ ) as compared to the stratus being a constant. 

DS3 DPAD is correct. 
DS3 Y analog revered. 
Wii-mote dpad's up-down reversed. 

I also noticed... And this might sound silly. In oceanhorn using DS3, it's almost like the pressure sensitive buttons have a deadzone applied. 

Other than that, the new hook seems to work perfectly.

**Comment by meancoot** [comment]
I tested with Lili and again found that the dpad and thumb sticks were reversed so I went ahead and changed the code to reflect that. I also fixed the WiiMote dpad and mapped the classic controller buttons. Plus I changed the code where GCControllerButtonInput's pressed property would only be set after value went above .25, which should fix the issues with DS3 buttons.

Next I need to add timeouts for wireless controller discovery, Lili never turns it off manually but BTstack has lag and dropped packets while running HCI Inquiries.

**Comment by OMGsus** [comment]
Testing new build now. 

I also noticed I was able to lock up some part of the stack by putting in a lot of inputs that were part of the deadzone. At least I think that's what did it. (Like partially pressing buttons to where it was a button press but didn't register in game). But if stuff like that occurs again and if I can repeat it, I'll open a separate issue. 

I think this one can be closed now though if you think too. I've had no issues with almost every game I tested invoking btstack now.

**Comment by OMGsus** [comment]
Ok MFi is weird or has some hidden compensating control...

Worms 3 with .25 deadzone pressure works flawless.(as far as button press response)
With Oceanhorn, you can feel the deadzone though. ???
On an mfi controller, both behave identical even though the stratus has pressure sensitive buttons as well. 

I think you are right that it should be .25 but both games behave the same way with the pressure sensitive buttons of the Stratus. 

Also in the latest, my sixaxis will pair, the game will think a controller is there, but no inputs get through. So I wasn't able to test the new pressure deadzone part. 

Also, the wii analogs might need to be boosted. Or maybe it was the packet drop lag thing you were talking about. 

I'll do some more testing with all three controllers and more games since I have a feeling some of these games have poor implementations. 

Closing this one though because I feel you fixed the invoking issue. I'll make separate reports with more detail if I can repeat them.
