### ISSUE TITLE
DualShock 4 support?

### ISSUE THREAD

**Issue by nintyapple** [meancoot/MFiWrapper#5]
Will DualShock 4 be added?

**Comment by OMGsus** [comment]
It will eventually. It's "easier" than ds3, but there's still a lot of work.

**Comment by nintyapple** [comment]
Thanks for the quick reply! Before you or I close it, any ETA on it?

**Comment by OMGsus** [comment]
I can't speak for meancoot. All I know is I looked at the protocol and tried to fork it myself to add ds4 but I'm REALLY new at developing for btstack so I'm stuck testing and guessing at this time. I said it was "easy" because the protocol seems very straight forward and the code meancoot is writing will let him (or someone) add new devices to the code. But this would be up to meancoot at this point. Again I can't speak for him, so I won't give an ETA.

**Comment by nintyapple** [comment]
Just noticed you weren't meancoot, :p How do I build/install this? It just says to install Theos and nothing else on the README

**Comment by OMGsus** [comment]
I guess there's a step or so missing but it depends what you are building for. 

There's an issue here that's closed now about building in mavericks. It might help. Other than that, I'll write a guide and maybe pull request it to the readme.

**Comment by nintyapple** [comment]
Thanks! I have Windows so that wouldn't help me, I'll close this now.

**Comment by meancoot** [comment]
I finally got a DualShock 4 today and adding support is going very well. I've got both pairing and input reports working and will make a push after I finish cleaning up the code.

**Comment by nintyapple** [comment]
Yay! This is for RetroArch, right? Can you help me install this?

**Comment by meancoot** [comment]
It can be used with any game that supports the new iOS7 game controller API. And will be used to replace BTstack code currently in RetroArch for all iOS versions, but I haven't pushed those changes yet.

I need to work on the pairing code some more tomorrow, but I will post prebuilt packages when it's ready.

**Comment by OMGsus** [comment]
Speaking of pairing... I found that my btstack install is getting more and more unreliable. Not sure if this makes any sense... I was gathering a lot of info/logs/caps on these issues with pairing and btstack getting stuck, but it's happening with MFiwrapper unloaded/uninstalled as well. Even uninstalled and re-installed btstack. Sometimes it will even stick in a pairing forever until reboot. Btstack will even say it's not running at all, but I'll have to cold-cycle the device to get bluetooth back. Not sure how to proceed.

**Comment by nintyapple** [comment]
The description now says DualShock 4 support, so its supported now?

**Comment by OMGsus** [comment]
The code is in to support the protocol, but the ds4 needs to be "pre-paired". Heh, get it? 

Meancoot is writing a utility to handle that part.

**Comment by nintyapple** [comment]
Lol. Alright, when that happens can you add a deb for it? Couldn't get the building on Windows link to work properly. :/

**Comment by nintyapple** [comment]
Anything on his utility?

**Comment by OMGsus** [comment]
It looks like wiipair will handle all initial pre-pairing including the ds4. So the name may change. The pairing process may change also due to how btstack works by default.

**Comment by nintyapple** [comment]
So if I have a friend that can build me this and WiiPair, will I be able to use this with my DS4?

**Comment by OMGsus** [comment]
Yes. :)

**Comment by nintyapple** [comment]
Alright, will have someone build later today and send some feedback. :)
