### ISSUE TITLE
How do I install MFiWrapper?

### ISSUE THREAD

**Issue by nintyapple** [meancoot/MFiWrapper#6]
I installed Theos but after that I really don't understand how to install this. Please help me!

**Comment by OMGsus** [comment]
Have you tried this?

http://sharedinstance.net/2013/12/build-on-windows/

Not sure how well this follows exactly what you need to do. 

One this you should do before running "make" is to put libBTSsack.dylib from your iPhone's /usr/lib in your $THEOS/lib dir

**Comment by nintyapple** [comment]
This didn't work for me, is there anyway you can set up a releases tab for debs?

**Comment by bru7us** [comment]
Patience.... it's not actually release ready yet. When it is, I'm sure the deb will be made very accessible.

Until then, you'll need to figure out a way to build it yourself, or a friend who can do it for you.
